name: ci

on:
  push:
  pull_request:
    branches: [main, develop]


jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: cargo check
      run: RUSTFLAGS="-D warnings" cargo check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
    - name: publish dry-run
      working-directory: ./ndhistogram
      run: cargo publish --locked --dry-run

  fmt:
    name: Lints
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - run: rustup component add rustfmt
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - run: rustup component add clippy
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
    - name: cargo doc
      run: RUSTDOCFLAGS="-D warnings" cargo doc
    - name: Setup python
      uses: actions/setup-python@v2
    - name: Run pre-commit hooks
      run: |
        pip install pre-commit \
        && pre-commit run --all

  nix:
    name: Nix support
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-21.11
    - uses: Swatinem/rust-cache@v1
    - name: Test in nix develop
      run: nix --extra-experimental-features nix-command --extra-experimental-features flakes develop -c cargo test --color=always
    - name: Test in nix-shell
      run: nix-shell shell.nix --run "cargo test --color=always"
